name: Deploy to AWS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build WAR
        run: ./gradlew clean war

      - name: Rename WAR
        run: mv build/libs/hello-world-1.0.war build/libs/ROOT.war

      - name: Verify war exists
        run: ls -la build/libs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::379197597292:role/github_worker
          aws-region: us-east-1

      - name: Create deployment zip
        run: |
          mkdir deploy
          cp build/libs/ROOT.war deploy/
          cd deploy
          zip -r ../deploy.zip .

      - name: Upload application bundle
        run: |
          aws s3 cp deploy.zip \
            s3://elasticbeanstalk-us-east-1-379197597292/deploy-${GITHUB_SHA}.zip

      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name InnoCICD \
            --version-label github-hello-world \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-379197597292",S3Key="deploy-${GITHUB_SHA}.zip"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name InnoCICD-env \
            --version-label github-hello-world